// Authority index service: loads, caches, and searches the per-entity
// record indexes generated by tools/build-index.js (index/index-{type}.json),
// and registers the local-* LOD providers.
// Everything on BA.authority. Classic script (no build step; loaded via <script>).

(function () {
  "use strict";

  var authority = window.BA.authority;

  var TTL_MS = 60 * 60 * 1000; // 1 hour
  var memory = {};   // type -> records array
  var inflight = {}; // type -> Promise
  var warned = {};   // type -> true (one fetch warning per session)

  function lsKey(type) { return "ba-index-" + type; }

  function lsGet(type) {
    try {
      var raw = localStorage.getItem(lsKey(type));
      return raw ? JSON.parse(raw) : null;
    } catch (e) { return null; }
  }

  function lsSet(type, data) {
    try {
      localStorage.setItem(lsKey(type), JSON.stringify({ fetchedAt: Date.now(), data: data }));
    } catch (e) { /* quota/privacy mode — memory cache still works */ }
  }

  function records(data) {
    return (data && Array.isArray(data.records)) ? data.records : [];
  }

  function warnOnce(type, msg) {
    if (!warned[type]) { console.warn("BA.authority: " + msg); warned[type] = true; }
  }

  // Public entry: route to the live-rebuild path or the prebuilt-index path.
  // Never rejects. Concurrent calls share one in-flight promise (per path).
  authority.load = function (type) {
    return liveEnabled() ? loadLive(type) : loadPrebuilt(type);
  };

  // Prebuilt index/*.json path (the default). Fetch + cache in memory + a 1 h
  // localStorage cache. Concurrent calls share one in-flight promise.
  function loadPrebuilt(type) {
    if (memory[type]) return Promise.resolve(memory[type]);
    if (inflight[type]) return inflight[type];

    var cached = lsGet(type);
    if (cached && (Date.now() - cached.fetchedAt) < TTL_MS) {
      memory[type] = records(cached.data);
      return Promise.resolve(memory[type]);
    }

    var url = (window.BA.config.indexPath || "index") + "/index-" + type + ".json";
    inflight[type] = fetch(url)
      .then(function (res) {
        if (!res.ok) throw new Error("HTTP " + res.status);
        return res.json();
      })
      .then(function (data) {
        memory[type] = records(data);
        lsSet(type, data);
        return memory[type];
      })
      .catch(function (err) {
        if (cached) {
          warnOnce(type, "using stale index for " + type + " (" + err.message + ")");
          memory[type] = records(cached.data);
        } else {
          warnOnce(type, "no index available for " + type + " (" + err.message + ")");
          memory[type] = [];
        }
        return memory[type];
      })
      .finally(function () { delete inflight[type]; });

    return inflight[type];
  }

  // ---------- live index path ----------
  // Session-only cache (NOT the 1 h localStorage cache): type -> {fetchedAt, records}.
  var liveCache = {};
  var liveInflight = {};

  function liveEnabled() {
    var c = window.BA.config.authorityLive;
    return !!(c && c.enabled);
  }
  function liveTtl() {
    var c = window.BA.config.authorityLive;
    return (c && c.ttlMs) || 60000;
  }

  // Rebuild the index for `type` from the repo's data/ folder. Resolves an array
  // of records, or null if the listing was unavailable. Fetch/parse errors on a
  // file reject (handled by loadLive's fallback).
  function buildLiveIndex(type) {
    return window.BA.github.listDataFiles(type).then(function (files) {
      if (!files) return null;
      return Promise.all(files.map(function (f) {
        return fetch(f.download_url)
          .then(function (res) {
            if (!res.ok) throw new Error("HTTP " + res.status + " for " + f.name);
            return res.text();
          })
          .then(function (text) { return liveRecord(type, f.name, text); });
      })).then(function (recs) {
        return recs.filter(Boolean).sort(function (a, b) {
          return parseInt(a.id, 10) - parseInt(b.id, 10);
        });
      });
    });
  }

  function liveRecord(type, name, text) {
    var id = name.replace(/\.xml$/, "");
    var doc = window.BA.util.parse(text); // throws on invalid XML
    var ex = extractLive(type, doc);
    var file = window.BA.config.dataDirs[type] + "/" + id + ".xml";
    return {
      id: id,
      uri: window.BA.config.baseUri + "/" + window.BA.config.entityPaths[type] + "/" + id,
      headword: ex.headword || ("[no headword] " + file),
      altNames: ex.altNames,
      file: file
    };
  }

  // Client-side mirror of tools/build-index.js `extract()` — KEEP ALIGNED with
  // that function (same per-type headword rules). Uses BA.util.q/qa/text and
  // scopes to <text> so the fixed teiHeader (which also holds <title>) is excluded.
  function extractLive(type, doc) {
    var U = window.BA.util;
    var body = U.q(doc, "text") || doc.documentElement;
    var headword = "", altNames = [];

    function texts(nodes) {
      return nodes.map(function (n) { return U.text(n); }).filter(Boolean);
    }
    function othersThan(list, hw) {
      var seen = {}, out = [];
      list.forEach(function (v) { if (v && v !== hw && !seen[v]) { seen[v] = true; out.push(v); } });
      return out;
    }

    if (type === "person") {
      headword = U.text(U.q(body, 'persName[@type="ba-headword"]/name'));
      altNames = othersThan(texts(U.qa(body, "persName/name")), headword);
    } else if (type === "place") {
      headword = U.text(U.q(body, 'placeName[@type="ba-headword"]'));
      altNames = othersThan(texts(U.qa(body, "placeName")), headword);
    } else if (type === "work") {
      headword = U.text(U.q(body, 'title[@type="ba-headword"]'));
      altNames = othersThan(texts(U.qa(body, "title")), headword);
    } else if (type === "manuscript") {
      var msName = U.text(U.q(body, "msName"));
      if (msName) {
        headword = msName;
      } else {
        var repo = U.text(U.q(body, "repository"));
        var idno = U.text(U.q(body, "idno"));
        headword = [repo, idno].filter(Boolean).join(" ").trim();
      }
      altNames = [];
    }
    return { headword: headword, altNames: altNames };
  }

  // Live load with ttlMs session cache; any failure warns and falls back to the
  // prebuilt-index path (so lookups keep working offline / when rate-limited).
  function loadLive(type) {
    var cached = liveCache[type];
    if (cached && (Date.now() - cached.fetchedAt) < liveTtl()) {
      return Promise.resolve(cached.records);
    }
    if (liveInflight[type]) return liveInflight[type];

    liveInflight[type] = buildLiveIndex(type)
      .then(function (recs) {
        if (recs === null) throw new Error("data listing unavailable");
        liveCache[type] = { fetchedAt: Date.now(), records: recs };
        memory[type] = recs; // keep resolve()/synchronous lookups working
        return recs;
      })
      .catch(function (err) {
        console.warn("BA.authority: live index unavailable for " + type +
          " (" + err.message + "); falling back to prebuilt index");
        delete liveCache[type];
        delete memory[type]; // force a fresh prebuilt fetch, not stale live data
        return loadPrebuilt(type);
      })
      .finally(function () { delete liveInflight[type]; });

    return liveInflight[type];
  }

  // Bypass all caches and re-fetch (works in both modes; clears the live cache too).
  authority.refresh = function (type) {
    delete memory[type];
    delete warned[type];
    delete liveCache[type];
    delete liveInflight[type];
    try { localStorage.removeItem(lsKey(type)); } catch (e) { /* ignore */ }
    return authority.load(type);
  };

  // Case- and diacritic-insensitive folding.
  function fold(s) {
    return (s || "").toLowerCase().normalize("NFD").replace(/\p{M}/gu, "");
  }

  // Exposed for reuse (collection filter uses the same folding logic).
  authority.fold = fold;

  // Substring search over headword + altNames; ranked headword-prefix,
  // headword-substring, then altName match; max 10.
  authority.search = function (type, term) {
    return authority.load(type).then(function (recs) {
      var needle = fold(term);
      if (!needle) return [];
      var hits = [];
      recs.forEach(function (rec) {
        var hw = fold(rec.headword);
        var score = null;
        var matchedAlt = null;
        if (hw.indexOf(needle) === 0) score = 0;
        else if (hw.indexOf(needle) !== -1) score = 1;
        else {
          (rec.altNames || []).some(function (alt) {
            if (fold(alt).indexOf(needle) !== -1) { matchedAlt = alt; return true; }
            return false;
          });
          if (matchedAlt !== null) score = 2;
        }
        if (score === null) return;
        hits.push({
          score: score,
          label: matchedAlt ? rec.headword + " — " + matchedAlt : rec.headword,
          uri: rec.uri,
          record: rec
        });
      });
      hits.sort(function (a, b) {
        return a.score - b.score || a.record.headword.localeCompare(b.record.headword);
      });
      return hits.slice(0, 10).map(function (h) {
        return { label: h.label, uri: h.uri, record: h.record };
      });
    });
  };

  // Synchronous lookup against the in-memory cache — call after load(type)
  // has resolved (editors load their linked types on page init).
  authority.resolve = function (type, uri) {
    var recs = memory[type] || [];
    for (var i = 0; i < recs.length; i++) {
      if (recs[i].uri === uri) return recs[i];
    }
    return null;
  };

  // Suggested next numeric id (max + 1; "1" for an empty index).
  authority.nextId = function (type) {
    return authority.load(type).then(function (recs) {
      var max = 0;
      recs.forEach(function (r) {
        var n = parseInt(r.id, 10);
        if (!isNaN(n) && n > max) max = n;
      });
      return String(max + 1);
    });
  };

  authority.checkCollision = function (type, id) {
    return authority.load(type).then(function (recs) {
      return recs.some(function (r) { return String(r.id) === String(id); });
    });
  };

  // Register the local-* LOD providers (registry).
  if (window.BA.lod && window.BA.lod.providers) {
    ["person", "place", "work", "manuscript"].forEach(function (t) {
      window.BA.lod.providers["local-" + t] = {
        label: "BA " + t + "s",
        search: function (term) { return authority.search(t, term); }
      };
    });
  }
})();
